netflixapp/urls.py
from django.urls import path
from .views import Home, ProfileList, ProfileCreate, MovieList, MovieDetail, PlayMovie

app_name = 'netflixapp'

urlpatterns = [
    path('', Home.as_view(), name="Home"),
    path('profiles/', ProfileList.as_view(), name="profile-list"),
    path('profiles/create/', ProfileCreate.as_view(), name="profile-create"),
    path('watch/<str:profile_id>/', MovieList.as_view(), name="movie-list"),
    path('watch/detail/<str:movie_id>/', MovieDetail.as_view(), name="movie-detail"),
    path('watch/play/<str:movie_id>/', PlayMovie.as_view(), name="play-movie"),
]

netflixprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('netflixapp.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

netflixapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

AGE_CHOICES = (
    ('All', 'All'),
    ('Kids', 'Kids'),
)

MOVIE_CHOICES = (
    ('seasonal', 'Seasonal'),
    ('single', 'Single'),
)

class CustomUser(AbstractUser):
    profiles = models.ManyToManyField('Profile', blank=True)

class Profile(models.Model):
    name = models.CharField(max_length=1000)
    age_limit = models.CharField(choices=AGE_CHOICES, max_length=10)
    uuid = models.UUIDField(default=uuid.uuid4)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=1000)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(default=uuid.uuid4)
    type = models.CharField(choices=MOVIE_CHOICES, max_length=10)
    video = models.ManyToManyField('Video')
    image = models.ImageField(upload_to='covers')
    age_limit = models.CharField(choices=AGE_CHOICES, max_length=10)

    def __str__(self):
        return self.title

class Video(models.Model):
    title = models.CharField(max_length=1000)
    file = models.FileField(upload_to='movies')

    def __str__(self):
        return self.title

netflixapp/forms.py
from django.forms import ModelForm
from netflixapp.models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['uuid']

netflixapp/views.py
import imp
from django.shortcuts import redirect, render
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from . forms import ProfileForm
from . models import Profile, Movie

class Home(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('netflixapp:profile-list')
        return render(request, 'index.html')

method_decorator(login_required, name='dispatch')
class ProfileList(View):
    def get(self, request, *args, **kwargs):
        
        profiles = request.user.profiles.all()

        context = {
            'profiles':profiles
        }
        return render(request, 'profilelist.html', context)

method_decorator(login_required, name='dispatch')
class ProfileCreate(View):
    def get(self, request, *args, **kwargs):
        form = ProfileForm()
        context = {
            'form':form
        }
        return render(request, 'profilecreate.html', context)

    def post(self, request, *args, **kwargs):
        form = ProfileForm(request.POST or None)
        if form.is_valid():
            profile = Profile.objects.create(**form.cleaned_data)
            if profile:
                request.user.profiles.add(profile)
                return redirect('netflixapp:profile-list')
        context = {
            'form':form
        }
        return render(request, 'profilecreate.html', context)

method_decorator(login_required, name='dispatch')
class MovieList(View):
    def get(self, request, profile_id, *args, **kwargs):
        try:
            profile = Profile.objects.get(uuid=profile_id)
            movies = Movie.objects.filter(age_limit=profile.age_limit)
            if profile not in request.user.profiles.all():
                return redirect('netflixapp:profile-list')

            context = {
            'movies':movies
            }

            return render(request, 'movielist.html', context)
        except Profile.DoesNotExist:
            return redirect('netflixapp:profile-list')

method_decorator(login_required, name='dispatch')
class MovieDetail(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            movie = Movie.objects.get(uuid=movie_id)
            
            context = {
                'movie':movie
            }

            return render(request, 'moviedetail.html', context)
        except Movie.DoesNotExist:
            return redirect('netflixapp:profile-list')

method_decorator(login_required, name='dispatch')
class PlayMovie(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            movie = Movie.objects.get(uuid=movie_id)
            movie = movie.video.values()
            
            context = {
                'movie':list(movie)
            }

            return render(request, 'playmovie.html', context)
        except Movie.DoesNotExist:
            return redirect('netflixapp:profile-list')

templates/base.html
{% load static %}
<html>
  <head>
    <meta name="description" content="Hello this is my first web page!." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'assets/src/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/login/style/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />
    <title>Netflix NG - Watch TV Shows Online, Watch Movies Online</title>
    <link rel="icon" href="http://pngimg.com/uploads/netflix/small/netflix_PNG15.png">
  </head>
  <body>
    <header>
      <nav class="navbar">
        <div class="navbar__brand">
          <img
            src="https://www.freepnglogos.com/uploads/netflix-logo-0.png"
            alt="logo"
            class="brand__logo"
          />
        </div>

        <div class="navbar__nav__items">
          <div class="nav__item">
            <div class="dropdown__container">
              <i class="fas fa-globe"></i>
              <select
                name="languages"
                id="languagesSelect"
                class="language__drop__down"
              >
                <option style=" color: black; " value="english" selected>English</option>
                <option  style=" color: black; "value="hindi">Afrikaan</option>
                <option  style=" color: black; "value="hindi">Korean</option>
                <option  style=" color: black; "value="hindi">French</option>
                <option  style="    color: black; "value="hindi">Spanish</option>
                <option  style=" color: black; "value="hindi">Chinnese</option>
              </select>
            </div>
          </div>
          {% if not request.user.is_authenticated %}
          <div class="nav__item">
            <a href="{% url 'account_login' %}" class="signin__button">Sign in</a>
          </div>
          {% else %}
          <div>
              <a class="signin__button" href="{% url 'account_logout' %}">Logout</a>
          </div>
          {% endif %}
        </div>
      </nav>
    </header>



    {% block content %}
    {% endblock content %}


    <footer>
      <div class="footer__row__1">
        <h4>Questions? Call 000-800-040-1843</h4>
      </div>
      <div class="footer__row__2">
        <div class="column__1">
          <p>FAQ</p>
          <p>Investor Relations</p>
          <p>Privacy</p>
          <p>Speed Test</p>
        </div>
        <div class="column__2">
          <p>Help Centre</p>
          <p>Jobs</p>
          <p>Cookie Preferences</p>
          <p>Legal Notices</p>
        </div>
        <div class="column__3">
          <p>Account</p>
          <p>Ways to Watch</p>
          <p>Corporate Information</p>
          <p>Only on Netflix</p>
        </div>
        <div class="column__4">
          <p>Media Centre</p>
          <p>Terms of Use</p>
          <p>Contact Us</p>
        </div>
      </div>
      <div class="footer__row__3">
        <div class="dropdown__container">
          <i class="fas fa-globe"></i>
          <select
            name="languages"
            id="languagesSelect"
            class="language__drop__down"
          >
            <option value="english" selected>English</option>
          </select>
        </div>
      </div>
      <div class="footer__row__4">
        <p>Netflix NG</p>
      </div>
    </footer>

    <script src="{% static 'assets/src/index.js' %}"></script>
  </body>
</html>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <main>
      <section class="hero">
        <div class="hero__bg__image__container">
          <img
            src="https://assets.nflxext.com/ffe/siteui/vlv3/9c5457b8-9ab0-4a04-9fc1-e608d5670f1a/710d74e0-7158-408e-8d9b-23c219dee5df/IN-en-20210719-popsignuptwoweeks-perspective_alpha_website_small.jpg"
            alt="BG hero image"
            class="hero__bg__image"
          />
        </div>
        <div class="hero__bg__overlay"></div>

        <div class="hero__card">
          <h1 class="hero__title">
            Unlimited Movies TV,<br />
            Shows and More.
          </h1>
          <p class="hero__subtitle">Watch anywhere and cancel anytime.</p>
          <p class="hero__description">
            Ready to watch? Enter your email to create or restart your
            membership .
          </p>

          <div class="email__form__container">
            <div class="form__container">
              <input style="color: black;" type="email" class="email__input" placeholder=" " />
              <label class="email__label">Email Address</label>
            </div>
            <a href="{% url 'account_login' %}" class="primary__button">
              Get Started <i class="fal fa-chevron-right"></i>
            </a>
          </div>
        </div>
      </section>
      <section class="features__container">
        <!-- Feature 1 -->
        <div class="feature">
          <div class="feature__details">
            <h3 class="feature__title">Enjoy on your TV.</h3>
            <h5 class="feature__sub__title">
              Watch on smart TVs, PlayStation, Xbox, Chromecast, Apple TV,
              Blu-ray players and more.
            </h5>
          </div>
          <div class="feature__image__container">
            <img
              src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/tv.png"
              alt="Feature image"
              class="feature__image"
            />
            <div class="feature__backgroud__video__container">
              <video
                autoplay=""
                loop=""
                muted=""
                class="feature__backgroud__video"
              >
                <source
                  src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/video-tv-in-0819.m4v"
                  type="video/mp4"
                />
              </video>
            </div>
          </div>
        </div>
        <!-- Feature 2 -->
        <div class="feature">
          <div class="feature__details">
            <h3 class="feature__title">
              Download your shows to watch offline.
            </h3>
            <h5 class="feature__sub__title">
              Save your favourites easily and always have something to watch.
            </h5>
          </div>
          <div class="feature__image__container">
            <img
              src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/mobile-0819.jpg"
              alt="Feature image"
              class="feature__image"
            />
            <div class="feature__2__poster__container">
              <div class="poster__container">
                <img
                  src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/boxshot.png"
                  alt="poster"
                  class="poster"
                />
              </div>
              <div class="poster__details">
                <h4>Stranger Things</h4>
                <h6>Downloading...</h6>
              </div>
              <div class="download__gif__container">
                <img
                  src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/download-icon.gif"
                  alt="downloading gif"
                  class="gif"
                />
              </div>
            </div>
          </div>
        </div>
        <!-- Feature 3 -->
        <div class="feature">
          <div class="feature__details">
            <h3 class="feature__title">Watch everywhere.</h3>
            <h5 class="feature__sub__title">
              Stream unlimited movies and TV shows on your phone, tablet,
              laptop, and TV.
            </h5>
          </div>
          <div class="feature__image__container feature__3__image__container">
            <img
              src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/device-pile-in.png"
              alt="Feature image"
              class="feature__image feature__3__image"
            />
            <div
              class="
                feature__backgroud__video__container
                feature__3__backgroud__video__container
              "
            >
              <video
                autoplay=""
                loop=""
                muted=""
                class="feature__backgroud__video feature__3__backgroud__video"
              >
                <source
                  src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/video-devices-in.m4v"
                  type="video/mp4"
                />
              </video>
            </div>
          </div>
        </div>
        <!-- Feature 4 -->
        <div class="feature">
          <div class="feature__details">
            <h3 class="feature__title">Create profiles for children.</h3>
            <h5 class="feature__sub__title">
              Send children on adventures with their favourite characters in a
              space made just for them—free with your membership.
            </h5>
          </div>
          <div class="feature__image__container">
            <img
              src="https://occ-0-4023-2164.1.nflxso.net/dnm/api/v6/19OhWN2dO19C9txTON9tvTFtefw/AAAABVxdX2WnFSp49eXb1do0euaj-F8upNImjofE77XStKhf5kUHG94DPlTiGYqPeYNtiox-82NWEK0Ls3CnLe3WWClGdiJP.png?r=5cf"
              alt="Feature image"
              class="feature__image"
            />
          </div>
        </div>
      </section>
      <section class="FAQ__list__container">
        <h1 class="FAQ__heading">Frequently Asked Questions</h1>
        <div class="FAQ__list">
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              What is Netflix?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>
                Netflix is a streaming service that offers a wide variety of
                award-winning TV shows, movies, anime, documentaries and more –
                on thousands of internet-connected devices.
              </p>
              <p>
                You can watch as much as you want, whenever you want, without a
                single ad – all for one low monthly price. There's always
                something new to discover, and new TV shows and movies are added
                every week!
              </p>
            </div>
          </div>
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              How much does netflix cost?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>
                Watch Netflix on your smartphone, tablet, Smart TV, laptop, or
                streaming device, all for one fixed monthly fee. Plans range
                from ₹ 199 to ₹ 799 a month. No extra costs, no contracts.
              </p>
            </div>
          </div>
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              Where can i watch?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>
                Watch anywhere, anytime, on an unlimited number of devices. Sign
                in with your Netflix account to watch instantly on the web at
                netflix.com from your personal computer or on any
                internet-connected device that offers the Netflix app, including
                smart TVs, smartphones, tablets, streaming media players and
                game consoles.
              </p>
              <p>
                You can also download your favourite shows with the iOS,
                Android, or Windows 10 app. Use downloads to watch while you're
                on the go and without an internet connection. Take Netflix with
                you anywhere.
              </p>
            </div>
          </div>
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              How do I cancel?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>
                Netflix is flexible. There are no annoying contracts and no commitments. You can easily cancel your account online in two clicks. There are no cancellation fees – start or stop your account anytime.
              </p>
            </div>
          </div>
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              What can I watch from Netflix?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>
                Netflix has an extensive library of feature films, documentaries, TV shows, anime, award-winning Netflix originals, and more. Watch as much as you want, anytime you want.
              </p>
            </div>
          </div>
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              Is Netflix good for kids?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>The Netflix Kids experience is included in your membership to give parents control while kids enjoy family-friendly TV shows and films in their own space.</p>
              <p>Kids profiles come with PIN-protected parental controls that let you restrict the maturity rating of content kids can watch and block specific titles you don’t want kids to see.</p>
            </div>
          </div>
        </div>
        <div class="FAQ__get__started__email">
          <h3>
            Ready to watch? Enter your email to create or restart your
            membership.
          </h3>
          <div class="email__form__container">
            <div class="form__container">
              <input type="email" class="email__input" placeholder=" " />
              <label class="email__label">Email Address</label>
            </div>
            <button class="primary__button">
              Get Started <i class="fal fa-chevron-right"></i>
            </button>
          </div>
        </div>
      </section>
    </main>

{% endblock content %}

templates/moviedetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='bg-primary_black text-cednter min-h-screen w-full shdowcase'>
        
       
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover" style="background-image: url('{{movie.image.url}}');">
            <div>
                <h2 style="text-shadow: 1px 4px 2px black;" class="text-6xl font-semibold text-white my-4">
                    {{movie.title|title}}
                </h2>
                <p style="text-shadow: 1px 2px 2px black;" class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{movie.description}}.
                </p>
                <div class="flex my-4">

                    <a style="padding: 10px; background: red;" href="{% url 'netflixapp:play-movie' movie_id=movie.uuid %}" class="flex items-center bg-red py-2 px-5 rounded-md">
                        <span class="material-symbols-outlined">
                            play_arrow
                        </span>
                        <span>
                            Play

                </a>
    
                    <button class="ml-4 text-white flex items-center bg-gray-500 bg-opacity-80 py-2 px-5 rounded-md">
                       
                        <ion-icon name="information-circle-outline" class="text-2xl" ></ion-icon>
                        <span class="ml-3 font-medium">
                            More Info
                        </span>
                    </button>
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <div style="margin-right: auto; margin-left: auto; display: inline-block;" >
                        <a style="padding: 10px; background: red;" href="{% url 'netflixapp:play-movie' movie_id=movie.uuid %}" class="flex items-center bg-red py-2 px-5 rounded-md">
                            <span class="material-symbols-outlined">
                                play_arrow
                            </span>
                            <span>
                                Play

                    </a>
                    <br><br>
                    </div>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Description
                </h2>
                <br>
                <div class="fldex justify-center  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                        <small>{{movie.description}}</small>
                    </p>
                </div>
            </div>
        </section>
        
    </main>
    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            
            if(scrollY>200){
                nav.classList.add('bg-gray-900')
          
            }else{
                nav.classList.remove('bg-gray-900')
                
            }
        })

    </script>

{% endblock content %}

templates/movielist.html
{% extends 'base.html' %}
{% load static %}
<!-- CSS only -->

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover" style="background-image: url('https://redcapes.it/wp-content/uploads/2020/06/975DF24B-D384-4AB8-8D2C-8D61DA0D15C8-scaled.jpeg');">
            <div>
                <h2 style="text-shadow: 1px 2px 2px black;" class="text-6xl font-semibold text-white my-4">
                   Artemis Fowl
                </h2>
                <p style="text-shadow: 1px 2px 2px black;" class="  w-11/12 md:w-5/12 font-medium text-white my-4">
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus repellendus odit perspiciatis nostrum culpa exercitationem quis. Ab obcaecati odio minus. Dolorum sapiente eaque, repellendus ea fugiat amet fuga libero at!
                </p>
                <div class="flex my-4">

                    
    
                    <button class="ml-4 text-white flex items-center bg-gray-500 bg-opacity-80 py-2 px-5 rounded-md">
                       
                        <ion-icon name="information-circle-outline" class="text-2xl" ></ion-icon>
                        <span class="ml-3 font-medium">#Trending</span>
                    </button>
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-center mb-4 text-2xl font-medium">
                    Popular on Netflix
                </h2>
                

        <div class="flex flex-wrap justify-center items-center w-12/12  md:w-12/12">
            {% for movie in movies %}
                <a href="{% url 'netflixapp:movie-detail' movie_id=movie.uuid %}">
                    <div style="height: 250px; width: 250px; object-fit: contain;" class="w-32 h-32 m-4  bg-blue-500 rounded-md cursor-pointer justify-center items-center flex-col flex">
                        <img src="{{movie.image.url}}" style="width: 245px; height: 245px; object-fit: cover;" >
                    </div>
                    <p class="text-center">{{movie.title}}</p>

                </a>
            {% endfor %}
            
        </div>
                
        </section>
        
    </main>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    {% endblock content %}

templates/playmovie.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='bg-primary_black h-full w-full '>
        {{movie|json_script:'movie_data'}}
        <video  controls class="w-full h-screen player"></video>
        
    </main>
    <script>
        const videoEl = document.querySelector('video')
        const movie_data = JSON.parse(document.getElementById('movie_data').textContent);
        const url = new URL(location.href)
        const video_param = parseInt(url.searchParams.get('epi'))?parseInt(url.searchParams.get('epi')):0
        videoEl.setAttribute('src', `http://localhost:8000/media/${movie_data[video_param].file}`)
    </script>
{% endblock content %}

templates/profilecreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class='bg-primary_black min-h-screen py-20 md:py-32 flex-col flex items-center' style="background-image: url('assets/background_netflix.jpg');">
        <div class="flex flex-wrap justify-center  w-10/12  md:w-6/12">
            <form class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg" method="POST">{% csrf_token %}
                <h1 class="text-4xl text-center text-gray-100 font-medium">
                    Create A Profile
                </h1>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Profile Name
                    </Label>
                    <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full" type="text" name="name" id="id_name" placeholder="Profile name">
                </div>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Maturity Level
                    </Label>
                    <select class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"  name="age_limit" id="id_age_limit" >
                        <option value="All">All</option>
                        <option value="Kids">Kids</option>
                       
                    </select>
                </div>
                <div class="flex justify-center items-center">
                    <button class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100" type="submit">Create Profile</button>
                </div>
            </form> 
        </div>
        
    </section>
    {% endblock content %}

templates/profilelist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class='bg-primary_black min-h-screen py-20 md:py-0 flex-col flex justify-center items-center' style="background-image: url('assets/background_netflix.jpg');">
        <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
            Who's watching ?
        </h2>

        <div class="flex flex-wrap justify-center items-center w-10/12  md:w-6/12">
            {% for profile in profiles %}
            <a href="{% url 'netflixapp:movie-list' profile_id=profile.uuid %}">
                <div class="w-32 h-32 m-4  bg-blue-500 rounded-md cursor-pointer justify-center items-center flex-col flex">
                    <p class="text-6xl" style="font-weight: 900;">{{ profile.name|slice:":1" }}</p>
                    <p>{{ profile.name }}</p>
                </div>
            </a>
            {% endfor %}
            
        </div>
        <div class="flex justify-center items-center">
            <a href="{% url 'netflixapp:profile-create' %}" class="px-4 py-2 rounded-md outline-none bg-gray-400 text-gray-100">
                Add A New Profile
            </a>
        </div>
    </section>

{% endblock content %}